version: '3.1'

services:

  db:
    image: postgres:13.11
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - 8080:8080