# Generated by Django 4.2.4 on 2023-08-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='BlogPost',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['mod_date'], 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
